// Auto-generated by precompile (RSD -> .h). DO NOT EDIT.
// Source: material.rsd

#pragma once

#include <string>
#include <map>
#include <array>
#include <cstddef>
#include "dolas_base.h"
#include "dolas_math.h"
#include "rsd_field.h"

namespace Dolas {

struct MaterialRSD;

struct MaterialRSD
{
    static constexpr const char* kFileSuffix = ".material";
    std::string vertex_shader;
    std::string pixel_shader;
    std::map<std::string, Vector4> vertex_shader_global_variables;
    std::map<std::string, Vector4> pixel_shader_global_variables;
    std::map<std::string, std::string> pixel_shader_texture;
    std::map<std::string, Float> parameter;

    static const std::array<RsdFieldDesc, 6> kFields;
};

inline const std::array<RsdFieldDesc, 6> MaterialRSD::kFields = {{
        {"vertex_shader", RsdFieldType::RawReference, offsetof(MaterialRSD, vertex_shader), nullptr, 0, nullptr, 0, nullptr},
        {"pixel_shader", RsdFieldType::RawReference, offsetof(MaterialRSD, pixel_shader), nullptr, 0, nullptr, 0, nullptr},
        {"vertex_shader_global_variables", RsdFieldType::MapStringVector4, offsetof(MaterialRSD, vertex_shader_global_variables), nullptr, 0, nullptr, 0, nullptr},
        {"pixel_shader_global_variables", RsdFieldType::MapStringVector4, offsetof(MaterialRSD, pixel_shader_global_variables), nullptr, 0, nullptr, 0, nullptr},
        {"pixel_shader_texture", RsdFieldType::MapStringRawReference, offsetof(MaterialRSD, pixel_shader_texture), nullptr, 0, nullptr, 0, nullptr},
        {"parameter", RsdFieldType::MapStringFloat, offsetof(MaterialRSD, parameter), nullptr, 0, nullptr, 0, nullptr},
}};

} // namespace Dolas
