// Auto-generated by precompile (RSD -> .h). DO NOT EDIT.
// Source: camera.rsd

#pragma once

#include <string>
#include <vector>
#include <map>
#include <set>

#include "base/dolas_base.h"
#include "core/dolas_math.h"

namespace Dolas {

struct CameraRSD
{
    static constexpr const char* kFileSuffix = ".camera";
    std::string camera_perspective_type;
    Vector3 position;
    Vector3 forward;
    Vector3 up;
    Float near_plane;
    Float far_plane;
    Float fov;
    Float aspect_ratio;
    Float window_width;
    Float window_height;
};

} // namespace Dolas
