// Auto-generated by precompile (RSD -> .h). DO NOT EDIT.
// Source: camera.rsd

#pragma once

#include <string>
#include <vector>
#include <map>
#include <set>
#include <array>
#include <cstddef>

#include "base/dolas_base.h"
#include "core/dolas_math.h"
#include "common/rsd_field.h"

namespace Dolas {

struct CameraRSD
{
    static constexpr const char* kFileSuffix = ".camera";
    std::string camera_perspective_type;
    Vector3 position;
    Vector3 forward;
    Vector3 up;
    Float near_plane;
    Float far_plane;
    Float fov;
    Float aspect_ratio;
    Float window_width;
    Float window_height;

    static const std::array<RsdFieldDesc, 10> kFields;
};

inline const std::array<RsdFieldDesc, 10> CameraRSD::kFields = {{
        {"camera_perspective_type", RsdFieldType::String, offsetof(CameraRSD, camera_perspective_type)},
        {"position", RsdFieldType::Vector3, offsetof(CameraRSD, position)},
        {"forward", RsdFieldType::Vector3, offsetof(CameraRSD, forward)},
        {"up", RsdFieldType::Vector3, offsetof(CameraRSD, up)},
        {"near_plane", RsdFieldType::FloatValue, offsetof(CameraRSD, near_plane)},
        {"far_plane", RsdFieldType::FloatValue, offsetof(CameraRSD, far_plane)},
        {"fov", RsdFieldType::FloatValue, offsetof(CameraRSD, fov)},
        {"aspect_ratio", RsdFieldType::FloatValue, offsetof(CameraRSD, aspect_ratio)},
        {"window_width", RsdFieldType::FloatValue, offsetof(CameraRSD, window_width)},
        {"window_height", RsdFieldType::FloatValue, offsetof(CameraRSD, window_height)},
}};

} // namespace Dolas
