// Auto-generated by precompile (RSD -> .h). DO NOT EDIT.
// Source: entity.rsd

#pragma once

#include <string>
#include <vector>
#include <map>
#include <set>
#include <cstddef>

#include "base/dolas_base.h"
#include "core/dolas_math.h"
#include "rsd/rsd_field.h"

namespace Dolas {

struct EntityRSD
{
    static constexpr const char* kFileSuffix = ".entity";
    std::string type;
    std::string mesh;
    std::string base_geometry;
    std::string material;

    static constexpr std::size_t kFieldCount = 4;
    static const RsdFieldDesc kFields[kFieldCount];
};

inline const RsdFieldDesc EntityRSD::kFields[EntityRSD::kFieldCount] = {
        {"type", RsdFieldType::String, offsetof(EntityRSD, type)},
        {"mesh", RsdFieldType::String, offsetof(EntityRSD, mesh)},
        {"base_geometry", RsdFieldType::String, offsetof(EntityRSD, base_geometry)},
        {"material", RsdFieldType::String, offsetof(EntityRSD, material)},
};

} // namespace Dolas
