// Auto-generated by precompile (RSD -> .h). DO NOT EDIT.
// Source: entity.rsd

#pragma once

#include <string>
#include <vector>
#include <map>
#include <set>

#include "base/dolas_base.h"
#include "core/dolas_math.h"

namespace Dolas {

struct EntityRSD
{
    static constexpr const char* kFileSuffix = ".entity";
    std::string type;
    std::string mesh;
    std::string base_geometry;
    std::string material;
};

} // namespace Dolas


