// Auto-generated by precompile (RSD -> .h). DO NOT EDIT.
// Source: material.rsd

#pragma once

#include <string>
#include <vector>
#include <map>
#include <set>
#include <array>
#include <cstddef>

#include "base/dolas_base.h"
#include "core/dolas_math.h"
#include "common/rsd_field.h"

namespace Dolas {

struct MaterialRSD
{
    static constexpr const char* kFileSuffix = ".material";
    std::string vertex_shader;
    std::string pixel_shader;
    std::map<std::string, Vector4> vertex_shader_global_variables;
    std::map<std::string, Vector4> pixel_shader_global_variables;
    std::map<std::string, std::string> pixel_shader_texture;
    std::map<std::string, Float> parameter;

    static const std::array<RsdFieldDesc, 6> kFields;
};

inline const std::array<RsdFieldDesc, 6> MaterialRSD::kFields = {{
        {"vertex_shader", RsdFieldType::String, offsetof(MaterialRSD, vertex_shader)},
        {"pixel_shader", RsdFieldType::String, offsetof(MaterialRSD, pixel_shader)},
        {"vertex_shader_global_variables", RsdFieldType::MapStringVector4, offsetof(MaterialRSD, vertex_shader_global_variables)},
        {"pixel_shader_global_variables", RsdFieldType::MapStringVector4, offsetof(MaterialRSD, pixel_shader_global_variables)},
        {"pixel_shader_texture", RsdFieldType::MapStringString, offsetof(MaterialRSD, pixel_shader_texture)},
        {"parameter", RsdFieldType::MapStringFloat, offsetof(MaterialRSD, parameter)},
}};

} // namespace Dolas
