// Auto-generated by precompile (RSD -> .h). DO NOT EDIT.
// Source: material.rsd

#pragma once

#include <string>
#include <vector>
#include <map>
#include <set>

#include "base/dolas_base.h"
#include "core/dolas_math.h"

namespace Dolas {

struct MaterialRSD
{
    static constexpr const char* kFileSuffix = ".material";
    std::string vertex_shader;
    std::string pixel_shader;
    std::map<std::string, Vector4> vertex_shader_global_variables;
    std::map<std::string, Vector4> pixel_shader_global_variables;
    std::map<std::string, std::string> pixel_shader_texture;
    std::map<std::string, Float> parameter;
};

} // namespace Dolas


