// Auto-generated by precompile (RSD -> .h). DO NOT EDIT.
// Source: mesh.rsd

#pragma once

#include <string>
#include <vector>
#include <map>
#include <set>
#include <cstddef>

#include "base/dolas_base.h"
#include "core/dolas_math.h"
#include "rsd/rsd_field.h"

namespace Dolas {

struct MeshRSD
{
    static constexpr const char* kFileSuffix = ".mesh";
    std::vector<Float> position;
    std::vector<Float> normal;
    std::vector<Float> uv0;
    std::vector<Float> uv1;
    std::vector<Float> color;
    std::vector<UInt> indices;
    std::string topology;
    std::string material;

    static constexpr std::size_t kFieldCount = 8;
    static const RsdFieldDesc kFields[kFieldCount];
};

inline const RsdFieldDesc MeshRSD::kFields[MeshRSD::kFieldCount] = {
        {"position", RsdFieldType::DynArrayFloat, offsetof(MeshRSD, position)},
        {"normal", RsdFieldType::DynArrayFloat, offsetof(MeshRSD, normal)},
        {"uv0", RsdFieldType::DynArrayFloat, offsetof(MeshRSD, uv0)},
        {"uv1", RsdFieldType::DynArrayFloat, offsetof(MeshRSD, uv1)},
        {"color", RsdFieldType::DynArrayFloat, offsetof(MeshRSD, color)},
        {"indices", RsdFieldType::DynArrayUInt, offsetof(MeshRSD, indices)},
        {"topology", RsdFieldType::Unsupported, offsetof(MeshRSD, topology)},
        {"material", RsdFieldType::Unsupported, offsetof(MeshRSD, material)},
};

} // namespace Dolas
