// Auto-generated by precompile (RSD -> .h). DO NOT EDIT.
// Source: scene.rsd

#pragma once

#include <string>
#include <vector>
#include <map>
#include <set>

#include "base/dolas_base.h"
#include "core/dolas_math.h"

namespace Dolas {

struct SceneRSD
{
    static constexpr const char* kFileSuffix = ".scene";
    // XML 片段：每个 <entity> / <model> 节点的原始 XML 字符串
    std::vector<std::string> entities;
    std::vector<std::string> models;
};

} // namespace Dolas



