// Auto-generated by precompile (RSD -> .h). DO NOT EDIT.
// Source: scene.rsd

#pragma once

#include <string>
#include <vector>
#include <map>
#include <set>
#include <array>
#include <cstddef>

#include "base/dolas_base.h"
#include "core/dolas_math.h"
#include "common/rsd_field.h"

namespace Dolas {

struct SceneRSD
{
    static constexpr const char* kFileSuffix = ".scene";
    std::vector<std::string> entities;
    std::vector<std::string> models;

    static const std::array<RsdFieldDesc, 2> kFields;
};

inline const std::array<RsdFieldDesc, 2> SceneRSD::kFields = {{
        {"entities", RsdFieldType::DynArrayXml, offsetof(SceneRSD, entities)},
        {"models", RsdFieldType::DynArrayXml, offsetof(SceneRSD, models)},
}};

} // namespace Dolas
