// Auto-generated by precompile (RSD -> .h). DO NOT EDIT.
// Source: topology.rsd

#pragma once

#include <string>
#include <vector>
#include <map>
#include <set>
#include <array>
#include <cstddef>

#include "base/dolas_base.h"
#include "core/dolas_math.h"
#include "common/rsd_field.h"

namespace Dolas {

struct TopologyRSD
{
    static constexpr const char* kFileSuffix = ".topology";

    static const std::array<RsdFieldDesc, 0> kFields;
};

inline const std::array<RsdFieldDesc, 0> TopologyRSD::kFields = {{
}};

} // namespace Dolas
