// Auto-generated by precompile (RSD -> .h). DO NOT EDIT.
// Source: topology.rsd

#pragma once

#include <string>
#include <vector>
#include <map>
#include <set>
#include <cstddef>

#include "base/dolas_base.h"
#include "core/dolas_math.h"
#include "rsd/rsd_field.h"

namespace Dolas {

struct TopologyRSD
{
    static constexpr const char* kFileSuffix = ".topology";

    static constexpr std::size_t kFieldCount = 0;
    static const RsdFieldDesc kFields[kFieldCount];
};

inline const RsdFieldDesc TopologyRSD::kFields[TopologyRSD::kFieldCount] = {
};

} // namespace Dolas
