if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "rsd_generate_one.cmake requires -DINPUT=... -DOUTPUT=...")
endif()

file(READ "${INPUT}" _rsd_text)

# 提取所有 "key" : "value" 键值对（rsd 约定：value 必为字符串）
# 兼容空格： "a" : "b" / "a":"b"
string(REGEX MATCHALL "\"([^\"]+)\"[ \t\r\n]*:[ \t\r\n]*\"([^\"]+)\"" _pairs "${_rsd_text}")

if(_pairs STREQUAL "")
    message(FATAL_ERROR "Invalid RSD (no key/value string pairs): ${INPUT}")
endif()

set(_class_name "")
set(_file_suffix "")
set(_field_lines "")
set(_need_map FALSE)
set(_need_set FALSE)
set(_need_vector FALSE)
set(_need_string FALSE)
set(_need_nlohmann_json FALSE)

function(_trim _in _out)
    set(_s "${_in}")
    string(REGEX REPLACE "^[ \t\r\n]+" "" _s "${_s}")
    string(REGEX REPLACE "[ \t\r\n]+$" "" _s "${_s}")
    set(${_out} "${_s}" PARENT_SCOPE)
endfunction()

function(_split_toplevel_commas _in _out_list)
    # 按顶层逗号拆分（忽略 < > 内的逗号）
    set(s "${_in}")
    set(depth 0)
    set(cur "")
    set(out "")
    string(LENGTH "${s}" n)
    math(EXPR last "${n}-1")
    foreach(i RANGE 0 ${last})
        string(SUBSTRING "${s}" ${i} 1 c)
        if(c STREQUAL "<")
            math(EXPR depth "${depth}+1")
        elseif(c STREQUAL ">")
            math(EXPR depth "${depth}-1")
        endif()

        if(c STREQUAL "," AND depth EQUAL 0)
            _trim("${cur}" cur_t)
            list(APPEND out "${cur_t}")
            set(cur "")
        else()
            set(cur "${cur}${c}")
        endif()
    endforeach()

    _trim("${cur}" cur_t)
    if(NOT cur_t STREQUAL "")
        list(APPEND out "${cur_t}")
    endif()
    set(${_out_list} "${out}" PARENT_SCOPE)
endfunction()

function(_cpp_type _spec _out_type _out_suffix)
    _trim("${_spec}" spec)

    # 基础类型
    if(spec STREQUAL "Float")
        set(t "Float")
        set(sfx "")
    elseif(spec STREQUAL "Double")
        set(t "Double")
        set(sfx "")
    elseif(spec STREQUAL "Int")
        set(t "Int")
        set(sfx "")
    elseif(spec STREQUAL "UInt")
        set(t "UInt")
        set(sfx "")
    elseif(spec STREQUAL "Bool")
        set(t "Bool")
        set(sfx "")
    elseif(spec STREQUAL "String")
        set(t "std::string")
        set(sfx "")
        set(_need_string TRUE PARENT_SCOPE)
    elseif(spec STREQUAL "Vector3")
        set(t "Vector3")
        set(sfx "")
    elseif(spec STREQUAL "Vector4")
        set(t "Vector4")
        set(sfx "")
    elseif(spec STREQUAL "Json")
        set(t "nlohmann::json")
        set(sfx "")
        set(_need_nlohmann_json TRUE PARENT_SCOPE)
    else()
        # 泛型/容器类型
        string(FIND "${spec}" "<" lt)
        string(FIND "${spec}" ">" gt REVERSE)
        if(lt GREATER -1 AND gt GREATER -1 AND gt GREATER lt)
            string(SUBSTRING "${spec}" 0 ${lt} base)
            math(EXPR inside_len "${gt}-${lt}-1")
            math(EXPR inside_off "${lt}+1")
            string(SUBSTRING "${spec}" ${inside_off} ${inside_len} inside)
            _trim("${base}" base)
            _trim("${inside}" inside)

            if(base STREQUAL "DynamicArray")
                _cpp_type("${inside}" inner_t inner_sfx)
                set(t "std::vector<${inner_t}>")
                set(sfx "")
                set(_need_vector TRUE PARENT_SCOPE)
            elseif(base STREQUAL "Set")
                _cpp_type("${inside}" inner_t inner_sfx)
                set(t "std::set<${inner_t}>")
                set(sfx "")
                set(_need_set TRUE PARENT_SCOPE)
            elseif(base STREQUAL "Map")
                _split_toplevel_commas("${inside}" args)
                list(LENGTH args argc)
                if(NOT argc EQUAL 2)
                    message(FATAL_ERROR "Map<K,V> expects 2 args: ${spec}")
                endif()
                list(GET args 0 kspec)
                list(GET args 1 vspec)
                _cpp_type("${kspec}" kt ksfx)
                _cpp_type("${vspec}" vt vsfx)
                set(t "std::map<${kt}, ${vt}>")
                set(sfx "")
                set(_need_map TRUE PARENT_SCOPE)
            elseif(base STREQUAL "StaticArray")
                _split_toplevel_commas("${inside}" args)
                list(LENGTH args argc)
                if(NOT argc EQUAL 2)
                    message(FATAL_ERROR "StaticArray<T,N> expects 2 args: ${spec}")
                endif()
                list(GET args 0 espec)
                list(GET args 1 nstr)
                _trim("${nstr}" nstr_t)
                if(NOT nstr_t MATCHES "^[0-9]+$")
                    message(FATAL_ERROR "StaticArray size must be integer: ${spec}")
                endif()
                _cpp_type("${espec}" et esfx)
                set(t "${et}")
                set(sfx "[${nstr_t}]")
            else()
                # 未知泛型：当成用户自定义模板
                set(t "${spec}")
                set(sfx "")
            endif()
        else()
            # 未知非泛型：当成自定义类型
            set(t "${spec}")
            set(sfx "")
        endif()
    endif()

    set(${_out_type} "${t}" PARENT_SCOPE)
    set(${_out_suffix} "${sfx}" PARENT_SCOPE)
endfunction()

foreach(p IN LISTS _pairs)
    # p 形如： "key" : "value" 整段
    string(REGEX REPLACE "^\"([^\"]+)\"[ \t\r\n]*:[ \t\r\n]*\"([^\"]+)\"$" "\\1" k "${p}")
    string(REGEX REPLACE "^\"([^\"]+)\"[ \t\r\n]*:[ \t\r\n]*\"([^\"]+)\"$" "\\2" v "${p}")

    if(k STREQUAL "class_name")
        set(_class_name "${v}")
        continue()
    endif()
    if(k STREQUAL "file_suffix")
        set(_file_suffix "${v}")
        continue()
    endif()

    _cpp_type("${v}" cpp_t cpp_sfx)
    set(_field_lines "${_field_lines}    ${cpp_t} ${k}${cpp_sfx};\n")
endforeach()

if(_class_name STREQUAL "")
    message(FATAL_ERROR "RSD missing required field: class_name (${INPUT})")
endif()
if(_file_suffix STREQUAL "")
    message(FATAL_ERROR "RSD missing required field: file_suffix (${INPUT})")
endif()

get_filename_component(_rsd_name "${INPUT}" NAME)
set(_header "")
string(APPEND _header "// Auto-generated by precompile (RSD -> .h). DO NOT EDIT.\n")
string(APPEND _header "// Source: ${_rsd_name}\n\n")
string(APPEND _header "#pragma once\n\n")

string(APPEND _header "#include <string>\n")
string(APPEND _header "#include <vector>\n")
string(APPEND _header "#include <map>\n")
string(APPEND _header "#include <set>\n")

if(_need_nlohmann_json)
    string(APPEND _header "#include <nlohmann/json.hpp>\n")
endif()

string(APPEND _header "\n")
string(APPEND _header "#include \"base/dolas_base.h\"\n")
string(APPEND _header "#include \"core/dolas_math.h\"\n\n")

string(APPEND _header "namespace Dolas {\n")
string(APPEND _header "struct ${_class_name}\n{\n")
string(APPEND _header "    static constexpr const char* kFileSuffix = \"${_file_suffix}\";\n")
string(APPEND _header "${_field_lines}")
string(APPEND _header "};\n\n")
string(APPEND _header "} // namespace Dolas\n")

# 仅当内容变化时才写文件，避免无意义的全量重编译
set(_old "")
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" _old)
endif()
if(NOT _old STREQUAL _header)
    get_filename_component(_out_dir "${OUTPUT}" DIRECTORY)
    file(MAKE_DIRECTORY "${_out_dir}")
    file(WRITE "${OUTPUT}" "${_header}")
endif()


