// Auto-generated by precompile (RSD -> .h). DO NOT EDIT.
// Source: camera.rsd

#pragma once

#include <array>
#include <cstddef>
#include "base/dolas_base.h"
#include "core/dolas_math.h"
#include "common/rsd_field.h"

namespace Dolas {

enum class CameraPerspectiveType : UInt
{
    Perspective = 0,
    Orthographic = 1,
};

inline const std::array<RsdEnumItemDesc, 2> kEnum_CameraPerspectiveType = {{
    {"Perspective", "透视", "perspective", 0},
    {"Orthographic", "正交", "orthographic", 1},
}};

struct CameraRSD;

struct CameraRSD
{
    static constexpr const char* kFileSuffix = ".camera";
    CameraPerspectiveType camera_perspective_type;
    Vector3 position;
    Vector3 forward;
    Vector3 up;
    Float near_plane;
    Float far_plane;
    Float fov;
    Float aspect_ratio;
    Float window_width;
    Float window_height;

    static const std::array<RsdFieldDesc, 10> kFields;
};

inline const std::array<RsdFieldDesc, 10> CameraRSD::kFields = {{
        {"camera_perspective_type", RsdFieldType::EnumUInt, offsetof(CameraRSD, camera_perspective_type), kEnum_CameraPerspectiveType.data(), kEnum_CameraPerspectiveType.size(), nullptr, 0, nullptr},
        {"position", RsdFieldType::Vector3, offsetof(CameraRSD, position), nullptr, 0, nullptr, 0, nullptr},
        {"forward", RsdFieldType::Vector3, offsetof(CameraRSD, forward), nullptr, 0, nullptr, 0, nullptr},
        {"up", RsdFieldType::Vector3, offsetof(CameraRSD, up), nullptr, 0, nullptr, 0, nullptr},
        {"near_plane", RsdFieldType::FloatValue, offsetof(CameraRSD, near_plane), nullptr, 0, nullptr, 0, nullptr},
        {"far_plane", RsdFieldType::FloatValue, offsetof(CameraRSD, far_plane), nullptr, 0, nullptr, 0, nullptr},
        {"fov", RsdFieldType::FloatValue, offsetof(CameraRSD, fov), nullptr, 0, nullptr, 0, nullptr},
        {"aspect_ratio", RsdFieldType::FloatValue, offsetof(CameraRSD, aspect_ratio), nullptr, 0, nullptr, 0, nullptr},
        {"window_width", RsdFieldType::FloatValue, offsetof(CameraRSD, window_width), nullptr, 0, nullptr, 0, nullptr},
        {"window_height", RsdFieldType::FloatValue, offsetof(CameraRSD, window_height), nullptr, 0, nullptr, 0, nullptr},
}};

} // namespace Dolas
