// Auto-generated by precompile (RSD -> .h). DO NOT EDIT.
// Source: entity.rsd

#pragma once

#include <string>
#include <vector>
#include <array>
#include <cstddef>
#include "base/dolas_base.h"
#include "core/dolas_math.h"
#include "common/rsd_field.h"

namespace Dolas {

struct EntityRSD;

struct EntityRSD
{
    static constexpr const char* kFileSuffix = ".entity";
    std::vector<std::string> meshes;

    static const std::array<RsdFieldDesc, 1> kFields;
};

inline const std::array<RsdFieldDesc, 1> EntityRSD::kFields = {{
        {"meshes", RsdFieldType::DynArrayString, offsetof(EntityRSD, meshes), nullptr, 0, nullptr, 0, nullptr},
}};

} // namespace Dolas
