// Auto-generated by precompile (RSD -> .h). DO NOT EDIT.
// Source: mesh.rsd

#pragma once

#include <string>
#include <vector>
#include <array>
#include <cstddef>
#include "base/dolas_base.h"
#include "core/dolas_math.h"
#include "common/rsd_field.h"

namespace Dolas {

enum class TopologyType : UInt
{
    TriangleList = 0,
    TriangleStrip = 1,
};

inline const std::array<RsdEnumItemDesc, 2> kEnum_TopologyType = {{
    {"TriangleList", "三角形列表", "triangleList", 0},
    {"TriangleStrip", "三角形扇", "triangleStrip", 1},
}};

struct MeshRSD;

struct MeshRSD
{
    static constexpr const char* kFileSuffix = ".mesh";
    std::vector<Float> position;
    std::vector<Float> normal;
    std::vector<Float> tangent;
    std::vector<Float> uv0;
    std::vector<Float> uv1;
    std::vector<Float> color;
    std::vector<UInt> indices;
    TopologyType topology;
    std::string material;

    static const std::array<RsdFieldDesc, 9> kFields;
};

inline const std::array<RsdFieldDesc, 9> MeshRSD::kFields = {{
        {"position", RsdFieldType::DynArrayFloat, offsetof(MeshRSD, position), nullptr, 0, nullptr, 0, nullptr},
        {"normal", RsdFieldType::DynArrayFloat, offsetof(MeshRSD, normal), nullptr, 0, nullptr, 0, nullptr},
        {"tangent", RsdFieldType::DynArrayFloat, offsetof(MeshRSD, tangent), nullptr, 0, nullptr, 0, nullptr},
        {"uv0", RsdFieldType::DynArrayFloat, offsetof(MeshRSD, uv0), nullptr, 0, nullptr, 0, nullptr},
        {"uv1", RsdFieldType::DynArrayFloat, offsetof(MeshRSD, uv1), nullptr, 0, nullptr, 0, nullptr},
        {"color", RsdFieldType::DynArrayFloat, offsetof(MeshRSD, color), nullptr, 0, nullptr, 0, nullptr},
        {"indices", RsdFieldType::DynArrayUInt, offsetof(MeshRSD, indices), nullptr, 0, nullptr, 0, nullptr},
        {"topology", RsdFieldType::EnumUInt, offsetof(MeshRSD, topology), kEnum_TopologyType.data(), kEnum_TopologyType.size(), nullptr, 0, nullptr},
        {"material", RsdFieldType::AssetReference, offsetof(MeshRSD, material), nullptr, 0, nullptr, 0, nullptr},
}};

} // namespace Dolas
