// Auto-generated by precompile (RSD -> .h). DO NOT EDIT.
// Source: scene.rsd

#pragma once

#include <string>
#include <vector>
#include <tinyxml2.h>
#include <array>
#include <cstddef>
#include "base/dolas_base.h"
#include "core/dolas_math.h"
#include "common/rsd_field.h"

namespace Dolas {

struct OneEntity;
struct SceneRSD;

struct OneEntity
{
    std::string entities;
    Vector3 entity_positions;
    Vector4 entity_rotations;
    Vector3 entity_scales;

    static const std::array<RsdFieldDesc, 4> kFields;
};

struct SceneRSD
{
    static constexpr const char* kFileSuffix = ".scene";
    std::vector<OneEntity> entities;

    static const std::array<RsdFieldDesc, 1> kFields;
};

inline bool ParseDynArrayObject_SceneRSD_entities(void* vecMember, const tinyxml2::XMLElement* container)
{
    auto* v = reinterpret_cast<std::vector<OneEntity>*>(vecMember);
    if (!container) return true;
    for (auto* child = container->FirstChildElement(); child; child = child->NextSiblingElement())
    {
        OneEntity tmp{};
        ParseRsdObjectFromXmlElement(child, &tmp, OneEntity::kFields.data(), OneEntity::kFields.size());
        v->push_back(tmp);
    }
    return true;
}

inline const std::array<RsdFieldDesc, 4> OneEntity::kFields = {{
        {"entities", RsdFieldType::AssetReference, offsetof(OneEntity, entities), nullptr, 0, nullptr, 0, nullptr},
        {"entity_positions", RsdFieldType::Vector3, offsetof(OneEntity, entity_positions), nullptr, 0, nullptr, 0, nullptr},
        {"entity_rotations", RsdFieldType::Vector4, offsetof(OneEntity, entity_rotations), nullptr, 0, nullptr, 0, nullptr},
        {"entity_scales", RsdFieldType::Vector3, offsetof(OneEntity, entity_scales), nullptr, 0, nullptr, 0, nullptr},
}};

inline const std::array<RsdFieldDesc, 1> SceneRSD::kFields = {{
        {"entities", RsdFieldType::DynArrayObject, offsetof(SceneRSD, entities), nullptr, 0, OneEntity::kFields.data(), OneEntity::kFields.size(), &ParseDynArrayObject_SceneRSD_entities},
}};

} // namespace Dolas
